### PR TITLE
unexpose open_file; add more docstrings

### PR DESCRIPTION
**Pull request by kmike**
open_file vs open is rather confusing when using from shell, so I added more docstrings

### CODE REVIEW

**Review by lopuhin — APPROVED** [review]
Thanks for clarification! Looks like we don't have ``open_file`` documented in the README at all, what do you think about making it private (``_open_file``)?

**Comment by kmike** [comment]
It would probably break some code, but I'm fine with that, as it will make library easier to use - let me make this change. We removed open_file from docs in 0.2 release.

**Comment by lopuhin** [comment]
Ah cool, thanks for checking! +1 to make this change as well 👍

**Comment by kmike** [comment]
@lopuhin could you please check it again?

**Review by lopuhin — APPROVED** [review]
Looks great, thanks for the improvements @kmike !

**Pull request merged**
